# Jekyll configuration

name: PgBouncer
description: PgBouncer 1.7.2中文手册(翻译：瀚高软件韩悦悦等)

# url is currently only used only for the RSS feed in feed.xml
url: https://pgbouncer.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: '/pgbouncer-doc'

# This can be '' to hide the Github nav button
github: 'pgbouncer/pgbouncer'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: false

permalink: /:year/:month/:title
paginate: 3

excerpt_separator: <!--more-->
highlighter: rouge
markdown: kramdown
exclude: ['README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'README.html', 'Makefile']